### ISSUE TITLE
Bug with Vapor tests

### ISSUE THREAD

**Issue by tannernelson** [antonmes/bbmark#1]
Vapor should be getting a lot more requests per second than these tests show. 

Looks like each request is getting stuck for the entire connection. Only 128 requests make it through. 

When running locally I get ~2k/s

**Comment by antonmes** [comment]
Please don't get hung up on Vapor, look at another results, most of them are the same. This is not Vapor tests bug, this is about linux-libdispatch or another underlying layer. This results are not final, this is why they are not included in the README.md yet.

btw, i guess you get ~2k/s on osx? try run it on linux.

**Comment by antonmes** [comment]
I'll update them soon, hope libdispatch feels better now. Plus i forgot to test Curassow. 😳

**Comment by tannernelson** [comment]
> try run it on linux.

Got 4k/s running it on a DO linux box.

Also, try doing `--header="Connection: keep-alive"`
